import { createVolumePyramidConfig } from '../pyramid/volume-pyramid.js';

// Builds a layoutSpec with pyramid config derived from per-volume hooks/state.
export function createVolumeLayoutSpec({
  volume,
  manifest,
  namesMap,
  placesState,
  buildPlacesLevel,
  placesChildrenHandler,
  getCatalogChildren,
  getCalendarMonths,
  getCalendarMonthChain,
  getCalendarDayChain,
  getWeekdayLetters,
  getBibleChapters,
  getBibleVerseItems,
  getBibleVerseChain,
  getBibleChapterChain,
  getBibleBooksForTestament,
  getBibleTestaments,
  prefetchBibleVerses,
  getApp,
  calendarModeRef,
  setCalendarMode,
  setCalendarMonthContext,
  bibleModeRef,
  setBibleMode,
  setBibleChapterContext,
  setBibleVerseContext,
  catalogModeRef,
  setCatalogMode,
  savePreInState,
  pyramidBuilder,
  launchGateway
} = {}) {
  const pyramid = createVolumePyramidConfig({
    volume,
    manifest,
    namesMap,
    placesState,
    buildPlacesLevel,
    placesChildrenHandler,
    getCatalogChildren,
    getCalendarMonths,
    getCalendarMonthChain,
    getCalendarDayChain,
    getWeekdayLetters,
    getBibleChapters,
    getBibleVerseItems,
    getBibleVerseChain,
    getBibleChapterChain,
    getBibleBooksForTestament,
    getBibleTestaments,
    prefetchBibleVerses,
    getApp,
    calendarModeRef,
    setCalendarMode,
    setCalendarMonthContext,
    bibleModeRef,
    setBibleMode,
    setBibleChapterContext,
    setBibleVerseContext,
    catalogModeRef,
    setCatalogMode,
    savePreInState,
    pyramidBuilder,
    launchGateway
  });
  return pyramid ? { pyramid } : {};
}
