// C.2 (Howell ruling: "split the catalog"): derive two files from the
// canonical mmdm_catalog.json —
//   catalog-lite.json   the structure the ring/pyramid needs at boot
//                       (every model minus its data{} prose block)
//   catalog-prose.json  { modelId: data{} } — grafted back in post-boot
// The canonical file remains the single source of truth and the review
// record; the derived pair is BUILD OUTPUT (gitignored, regenerated by
// `npm run build`, shipped by sync-to-server.sh).
import { readFileSync, writeFileSync } from 'node:fs';

const SRC = new URL('../data/mmdm/mmdm_catalog.json', import.meta.url).pathname;
const LITE = new URL('../data/mmdm/catalog-lite.json', import.meta.url).pathname;
const PROSE = new URL('../data/mmdm/catalog-prose.json', import.meta.url).pathname;

const catalog = JSON.parse(readFileSync(SRC, 'utf8'));
const prose = {};
let stripped = 0, kept = 0;

function walk(node) {
  if (Array.isArray(node)) { node.forEach(walk); return; }
  if (!node || typeof node !== 'object') return;
  if (node.engine_model !== undefined && node.data && typeof node.data === 'object') {
    if (node.id) {
      prose[node.id] = node.data;
      delete node.data;
      stripped++;
    } else {
      kept++; // no id to key on — prose stays inline, boot pays for it
    }
  }
  Object.values(node).forEach(walk);
}
walk(catalog);

writeFileSync(LITE, JSON.stringify(catalog));
writeFileSync(PROSE, JSON.stringify(prose));
const kb = p => Math.round(readFileSync(p).length / 1024);
console.log(`split-catalog: ${stripped} models stripped (${kept} kept inline) → lite ${kb(LITE)}KB + prose ${kb(PROSE)}KB (canonical ${kb(SRC)}KB)`);
